apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "kafka-ops-operator.labels" . | nindent 4 }}
  name: {{ include "kafka-ops-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
